UPDATE product SET brand_id = 7, brand = 'Egemen', specifications = '{}' WHERE id = 1;
UPDATE product SET brand_id = 7, brand = 'Egemen', specifications = '{}' WHERE id = 5;
UPDATE product SET brand_id = 7, brand = 'Egemen', specifications = '{"gauge": "24", "length": "90mm", "bevel type": "Quincke", "introducer needle": "included", "hub": "transparent"}' WHERE id = 9;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 16;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 23;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 30;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 31;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 38;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 41;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 42;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 43;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 45;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{"Length": "20cm", "Tubing Type": "Smoothbore", "Output Connections": "22m/15f"}' WHERE id = 54;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 57;
UPDATE product SET brand_id = 1, brand = 'CULLINAN', specifications = '{}' WHERE id = 59;
UPDATE product SET brand_id = 1, brand = 'CULLINAN', specifications = '{}' WHERE id = 60;
UPDATE product SET brand_id = 7, brand = 'Egemen', specifications = '{"R\u00e9f\u00e9rence Produit": "TMT-EPIS18903", "Type de Kit": "Kit P\u00e9ridural Complet", "Aiguille de Tuohy": "Incluse", "Cath\u00e9ter P\u00e9ridural": "Radio-opaque", "Seringue Perte de R\u00e9sistance": "Incluse", "Filtre Antibact\u00e9rien": "Inclus", "Connecteur": "Luer-Lock", "St\u00e9rilisation": "Oxyde d''\u00e9thyl\u00e8ne", "Usage": "Usage unique"}' WHERE id = 63;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 500;
UPDATE product SET brand_id = 1, brand = 'RUSCH AR', specifications = '{}' WHERE id = 502;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 505;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 508;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 509;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 510;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 514;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 516;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{"Size": "CH12"}' WHERE id = 517;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 522;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 523;
UPDATE product SET brand_id = 8, brand = 'Coloplast', specifications = '{}' WHERE id = 526;
UPDATE product SET brand_id = 1, brand = 'OTU', specifications = '{}' WHERE id = 530;
UPDATE product SET brand_id = 1, brand = 'OTU', specifications = '{}' WHERE id = 531;
UPDATE product SET brand_id = 1, brand = 'OTU', specifications = '{}' WHERE id = 532;
UPDATE product SET brand_id = 1, brand = 'OTU', specifications = '{}' WHERE id = 533;
UPDATE product SET brand_id = 1, brand = 'SWAN MORTON', specifications = '{}' WHERE id = 534;
UPDATE product SET brand_id = 1, brand = 'GUILLIN', specifications = '{}' WHERE id = 536;
UPDATE product SET brand_id = 1, brand = 'NEOMEDIC', specifications = '{"volume": "1ml", "needle_gauge": "27G", "needle_length": "0.5", "connection_type": "Luer Slip", "material": "Polypropylene/Polyethylene", "sterility": "true", "single_use": "true"}' WHERE id = 553;
UPDATE product SET brand_id = 1, brand = 'NEOMEDIC', specifications = '{"size": "8.0", "material": "Natural rubber latex", "sterility": "true", "powder_free": "false", "single_use": "true", "latex_free": "false"}' WHERE id = 554;
UPDATE product SET brand_id = 1, brand = 'NEOMEDIC', specifications = '{"volume": "50ml", "needle_gauge": "21G", "needle_length": "1.5", "connection_type": "Luer Slip", "material": "Polypropylene/Polyethylene", "sterility": "true", "single_use": "true", "latex_free": "true"}' WHERE id = 558;
UPDATE product SET brand_id = 1, brand = 'NEOMEDIC', specifications = '{"volume": "1ml", "needle_gauge": "29G", "needle_length": "0.5", "connection_type": "Fixed Needle", "material": "Polypropylene/Polyethylene", "sterility": "true", "single_use": "true"}' WHERE id = 559;
UPDATE product SET brand_id = 1, brand = 'NEOMEDIC', specifications = '{"volume": "20ml", "needle_gauge": "21G", "connection_type": "Luer Slip", "material": "Polypropylene/Polyethylene", "sterility": "true", "single_use": "true", "latex_free": "true"}' WHERE id = 561;
UPDATE product SET brand_id = 1, brand = 'NEOMEDIC', specifications = '{"size": "S", "material": "Natural rubber latex", "sterility": "false", "powder_free": "false", "single_use": "true", "latex_free": "false"}' WHERE id = 562;
UPDATE product SET brand_id = 1, brand = 'NEOMEDIC', specifications = '{"volume": "50ml", "needle_gauge": "21G", "connection_type": "Catheter Tip", "material": "Polypropylene/Polyethylene", "sterility": "true", "single_use": "true", "latex_free": "true"}' WHERE id = 564;
UPDATE product SET brand_id = 6, brand = 'Pharmaplast', specifications = '{}' WHERE id = 566;
UPDATE product SET brand_id = 1, brand = 'FITONE GROUP', specifications = '{}' WHERE id = 567;
UPDATE product SET brand_id = 6, brand = 'Pharmaplast', specifications = '{}' WHERE id = 568;
UPDATE product SET brand_id = 5, brand = 'Greatcare', specifications = '{}' WHERE id = 569;
UPDATE product SET brand_id = 5, brand = 'Greatcare', specifications = '{}' WHERE id = 570;
UPDATE product SET brand_id = 5, brand = 'Greatcare', specifications = '{}' WHERE id = 571;