name = "mediunit-backend"
compatibility_date = "2024-02-25"
compatibility_flags = [ "python_workers" ]
main = "./worker.py"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "mediunit_db"
database_id = "87f7686a-bba3-4b9a-9407-3d261e8ff224"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "mediunit-storage"
