UPDATE product 
SET specifications = '{"Matériau": "Acier Carbone de qualité médicale", "Stérilisation": "Rayonnement Gamma (25 kGy)", "Compatibilité Manches": "Manches N°3, 3L, 5, 7", "Conditionnement": "Boîte de 100 unités (emballage individuel en aluminium)", "Usage Clinique": "Chirurgie générale, incisions de précision"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Matériau</strong> : Acier Carbone de qualité médicale. <strong>Stérilisation</strong> : Rayonnement Gamma (25 kGy). <strong>Compatibilité Manches</strong> : Manches N°3, 3L, 5, 7. <strong>Conditionnement</strong> : Boîte de 100 unités (emballage individuel en aluminium). <strong>Usage Clinique</strong> : Chirurgie générale, incisions de précision. </p>'
WHERE sku = 'PAR-BLADE-11';
UPDATE product 
SET specifications = '{"Matériau": "Acier Carbone de qualité médicale", "Stérilisation": "Rayonnement Gamma (25 kGy)", "Compatibilité Manches": "Manches N°3, 3L, 5, 7", "Conditionnement": "Boîte de 100 unités (emballage individuel en aluminium)", "Usage Clinique": "Dissections délicates, chirurgie dermatologique"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Matériau</strong> : Acier Carbone de qualité médicale. <strong>Stérilisation</strong> : Rayonnement Gamma (25 kGy). <strong>Compatibilité Manches</strong> : Manches N°3, 3L, 5, 7. <strong>Conditionnement</strong> : Boîte de 100 unités (emballage individuel en aluminium). <strong>Usage Clinique</strong> : Dissections délicates, chirurgie dermatologique. </p>'
WHERE sku = 'PAR-BLADE-15';
UPDATE product 
SET specifications = '{"Type": "Corruguée, extensible", "Volume Mort": "15 ml (minimise la réinhalation de CO2)", "Connectique": "Raccords standard 22F/15M - 15F", "Stérilisation": "Usage unique, conditionnement stérile", "Usage Clinique": "Connexion entre le circuit respiratoire et la sonde de patient"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Type</strong> : Corruguée, extensible. <strong>Volume Mort</strong> : 15 ml (minimise la réinhalation de CO2). <strong>Connectique</strong> : Raccords standard 22F/15M - 15F. <strong>Stérilisation</strong> : Usage unique, conditionnement stérile. <strong>Usage Clinique</strong> : Connexion entre le circuit respiratoire et la sonde de patient. </p>'
WHERE sku = 'RUS191014-000200';
UPDATE product 
SET specifications = '{"Type de Filtre": "HMEF (Échangeur Chaleur et Humidité + Filtre Bactérien)", "Efficacité (BFE/VFE)": "> 99.999%", "Résistance au flux": "1.5 cmH2O à 30 L/min", "Volume Mort": "45 ml", "Sortie Hydrique": "32 mg/H2O à VT 500ml", "Usage Clinique": "Anesthésie et réanimation (Protège le patient et le respirateur)"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Type de Filtre</strong> : HMEF (Échangeur Chaleur et Humidité + Filtre Bactérien). <strong>Efficacité (BFE/VFE)</strong> : > 99.999%. <strong>Résistance au flux</strong> : 1.5 cmH2O à 30 L/min. <strong>Volume Mort</strong> : 45 ml. <strong>Sortie Hydrique</strong> : 32 mg/H2O à VT 500ml. <strong>Usage Clinique</strong> : Anesthésie et réanimation (Protège le patient et le respirateur). </p>'
WHERE sku = 'RUS18402T';
UPDATE product 
SET specifications = '{"Matériau": "Polymère semi-rigide (PE) et insert rigide (PP)", "Design": "Forme anatomique anti-morsure avec code couleur ISO", "Stérilisation": "Oxyde d''éthylène (EO)", "Usage Clinique": "Maintien de la perméabilité des voies aériennes supérieures"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Matériau</strong> : Polymère semi-rigide (PE) et insert rigide (PP). <strong>Design</strong> : Forme anatomique anti-morsure avec code couleur ISO. <strong>Stérilisation</strong> : Oxyde d''éthylène (EO). <strong>Usage Clinique</strong> : Maintien de la perméabilité des voies aériennes supérieures. </p>'
WHERE sku = 'RUS124900-000001';
UPDATE product 
SET specifications = '{"Matériau": "PVC médical thermosensible transparent", "Ballonnet": "Oui, profil bas, basse pression / haut volume (BPHV)", "Biseau": "Type Murphy avec œil atraumatique", "Radio-opacité": "Ligne radio-opaque continue sur toute la longueur", "Usage Clinique": "Intubation trachéale ventilatoire prolongée"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Matériau</strong> : PVC médical thermosensible transparent. <strong>Ballonnet</strong> : Oui, profil bas, basse pression / haut volume (BPHV). <strong>Biseau</strong> : Type Murphy avec œil atraumatique. <strong>Radio-opacité</strong> : Ligne radio-opaque continue sur toute la longueur. <strong>Usage Clinique</strong> : Intubation trachéale ventilatoire prolongée. </p>'
WHERE sku = 'RUS112480-000030';
UPDATE product 
SET specifications = '{"Matériau": "PVC médical thermosensible transparent", "Ballonnet": "Non (Idéal usage pédiatrique strict)", "Biseau": "Type Murphy atraumatique", "Marquage": "Graduations d''insertion claires (cm)", "Usage Clinique": "Intubation néonatale / pédiatrique courte durée"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Matériau</strong> : PVC médical thermosensible transparent. <strong>Ballonnet</strong> : Non (Idéal usage pédiatrique strict). <strong>Biseau</strong> : Type Murphy atraumatique. <strong>Marquage</strong> : Graduations d''insertion claires (cm). <strong>Usage Clinique</strong> : Intubation néonatale / pédiatrique courte durée. </p>'
WHERE sku = 'RUS100380-000020';
UPDATE product 
SET specifications = '{"Matériau": "Silicone sans latex, auto-adhésif", "Fixation": "Adhésif acrylique intégré, respectueux de la peau", "Design": "Système anti-pliure (assure un flux continu)", "Usage Clinique": "Incontinence urinaire masculine"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Matériau</strong> : Silicone sans latex, auto-adhésif. <strong>Fixation</strong> : Adhésif acrylique intégré, respectueux de la peau. <strong>Design</strong> : Système anti-pliure (assure un flux continu). <strong>Usage Clinique</strong> : Incontinence urinaire masculine. </p>'
WHERE sku = 'COL051350';
UPDATE product 
SET specifications = '{"Matériau": "PVC souple avec revêtement hydrophile PVP", "Lubrification": "Pré-lubrifiée, prête à l''emploi après immersion dans l''eau", "Design": "Œils polis au feu pour insertion atraumatique", "Usage Clinique": "Sondage auto-intermittent (SAI), prévention des micro-traumatismes urétraux"}',
    description = description || '<p>Ce dispositif médical est conçu avec des matériaux de haute qualité clinique. Principales caractéristiques techniques : <strong>Matériau</strong> : PVC souple avec revêtement hydrophile PVP. <strong>Lubrification</strong> : Pré-lubrifiée, prête à l''emploi après immersion dans l''eau. <strong>Design</strong> : Œils polis au feu pour insertion atraumatique. <strong>Usage Clinique</strong> : Sondage auto-intermittent (SAI), prévention des micro-traumatismes urétraux. </p>'
WHERE sku = 'COL284140';