-- FINAL COMPREHENSIVE SLUG STANDARDIZATION
-- Run on Cloudflare D1 (npx wrangler d1 execute mediunit-db --remote --file=...)
UPDATE category SET slug = 'anesthesie' WHERE name = 'Anesthesie';
UPDATE category SET slug = 'seringues' WHERE name = 'Seringues';
UPDATE category SET slug = 'urologie' WHERE name = 'Urologie';
UPDATE category SET slug = 'kits-cliniques' WHERE name = 'Kits Cliniques';
UPDATE category SET slug = 'gants-chirurgicaux' WHERE name = 'Gants Chirurgicaux';
UPDATE category SET slug = 'sparadraps-non-tissés' WHERE name = 'Sparadraps Non Tissés';
UPDATE category SET slug = 'gants-d-examen' WHERE name = 'Gants D''Examen';
UPDATE category SET slug = 'orl' WHERE name = 'Orl';
UPDATE category SET slug = 'bloc-operatoire' WHERE name = 'Bloc Opératoire' OR name = 'Bloc-Operatoire';
UPDATE category SET slug = 'lames-de-bistouri' WHERE name = 'Lames de Bistouri';
UPDATE product SET slug = 'kit-peridural-egemen' WHERE sku = 'TMT-EPIS18903';
UPDATE product SET slug = 'neo176550g-syringe-a-embout-de-catheter-' WHERE sku = 'NEO176550G';
UPDATE product SET slug = 'coloplast-poche-uro-2-pieces-multi-tailles' WHERE sku = 'COL142280';
UPDATE product SET slug = 'kit-premiers-secours-urgence' WHERE sku = 'KIT-URG-001';
UPDATE product SET slug = 'sonde-d-intubation-armee-multi-tailles' WHERE sku = 'RUS104202-000035';
UPDATE product SET slug = 'gants-chirurgicaux-en-latex-steriles-multi-tailles' WHERE sku = 'NEO152080';
UPDATE product SET slug = 'pharmaplast-pansements-espuma-ag-multi-tailles' WHERE sku = 'PHA-YESHAC';
UPDATE product SET slug = 'sonde-d-intubation-avec-ballonnet-multi-tailles' WHERE sku = 'RUS112480-000030';
UPDATE product SET slug = 'aiguille-de-rachianesthesie-pointe-crayon-multi-tailles' WHERE sku = 'TMT-SPPK-2590';
UPDATE product SET slug = 'coloplast-sonde-easicath-pediatrique-multi-tailles' WHERE sku = 'COL050080';
UPDATE product SET slug = 'rus116100-000260-kit-de-sonde-d''intubation-sele' WHERE sku = 'RUS116100-000260';
UPDATE product SET slug = 'masque-larynge-fast-track-multi-tailles' WHERE sku = 'LMA135130';
UPDATE product SET slug = 'kit-excision-dermatologique' WHERE sku = 'KIT-DERM-001';
UPDATE product SET slug = 'coloplast-sonde-easicath-homme-multi-tailles' WHERE sku = 'COL053520';
UPDATE product SET slug = 'coloplast-sonde-intermittente-homme-multi-tailles' WHERE sku = 'COL284140';
UPDATE product SET slug = 'aiguille-de-ponction-lombaire-multi-tailles' WHERE sku = 'TMT-SPQ-1990';
UPDATE product SET slug = 'speculum-vaginal-greatcare-multi-tailles' WHERE sku = 'GRE-ABRAKQ';
UPDATE product SET slug = 'coloplast-conveen-etui-penien-multi-tailles' WHERE sku = 'COL051350';
UPDATE product SET slug = 'culci1-042-05-laryngoscope-macintosh-–-culli' WHERE sku = 'CULCI1-042/05';
UPDATE product SET slug = 'fix254550-pharmafix®-—-pansement-de-fixa' WHERE sku = 'FIX254550';
UPDATE product SET slug = 'rus100380-000050-sonde-d''intubation-subglottiqu' WHERE sku = 'RUS100380-000050';
UPDATE product SET slug = 'aprtf0ubcd-gants-d-examen-en-latex-steril' WHERE sku = 'APRtF0UbCd';
UPDATE product SET slug = 'kit-tracheofix-avec-ballonnet-multi-tailles' WHERE sku = 'RUS121420-000070';
UPDATE product SET slug = 'lame-de-bistouri-multi-tailles' WHERE sku = 'SW158511';
UPDATE product SET slug = 'neo176501-seringue-luer-slip-de-1-ml-ave' WHERE sku = 'NEO176501';
UPDATE product SET slug = 'rus116100-000410-kit-de-sonde-d''intubation-sele' WHERE sku = 'RUS116100-000410';
UPDATE product SET slug = 'rus18402t-filtre-coude-combine-echangeur' WHERE sku = 'RUS18402T';
UPDATE product SET slug = 'gants-de-chirurgie-en-latex-non-poudres-multi-tailles' WHERE sku = 'GUIMTPC75';
UPDATE product SET slug = 'otu-100rr-ureteroscope-souple-a-usage-un' WHERE sku = 'OTU-100RR';
UPDATE product SET slug = 'coloplast-sonde-easicath-femme-multi-tailles' WHERE sku = 'COL053720';
UPDATE product SET slug = 'kit-suture-standard' WHERE sku = 'KIT-SUTURE-001';
UPDATE product SET slug = 'coloplast-sonde-intermittente-femme-multi-tailles' WHERE sku = 'COL285120';
UPDATE product SET slug = 'speculum-auriculaire-greatcare-multi-tailles' WHERE sku = 'GRE-CKFPVX';
UPDATE product SET slug = 'aiguille-spinale-biseau-quincke-multi-tailles' WHERE sku = 'TMTSPQK2490';
UPDATE product SET slug = 'col287080-coloplast-sonde-pour-sondage-i' WHERE sku = 'COL287080';
UPDATE product SET slug = 'monture-de-catheter-multi-tailles' WHERE sku = 'RUS191014-000200';
UPDATE product SET slug = 'gants-d-examen-non-steriles-multi-tailles' WHERE sku = 'NEO152100';
UPDATE product SET slug = 'sonde-d-intubation-sans-ballonnet-multi-tailles' WHERE sku = 'RUS100380-000020';
UPDATE product SET slug = 'kit-tracheofix-sans-ballonnet-multi-tailles' WHERE sku = 'RUS121415-000100';
UPDATE product SET slug = 'laryngoscope-avec-lames-multi-tailles' WHERE sku = 'HUGVL4R432';
UPDATE product SET slug = 'kit-consultation-generaliste' WHERE sku = 'KIT-GEN-001';
UPDATE product SET slug = 'canule-de-guedel-multi-tailles' WHERE sku = 'RUS124900-000001';
UPDATE product SET slug = 'neo176501-29-seringue-a-insuline-de-1-ml-av' WHERE sku = 'NEO176501/29';
UPDATE product SET slug = 'col174800-coloplast-poche-uro-1-piece-en' WHERE sku = 'COL174800';
UPDATE product SET slug = 'col175210-coloplast-poche-uro-1-piece-al' WHERE sku = 'COL175210';
UPDATE product SET slug = 'seringue-luer-slip-3-pieces-multi-tailles' WHERE sku = 'NEO176550SLIP';
UPDATE product SET slug = 'otu-c380rr-cystoscope-souple-usage-unique' WHERE sku = 'OTU-C380RR';
UPDATE product SET slug = 'kit-examen-gynecologique' WHERE sku = 'KIT-GYN-001';
UPDATE product SET slug = 'kit-sondage-urinaire' WHERE sku = 'KIT-URO-001';
UPDATE product SET slug = 'rus116200-000390-kit-de-sonde-d''intubation-sele' WHERE sku = 'RUS116200-000390';
UPDATE product SET slug = 'otu-100sl-ureteroscope-souple-usage-uniq' WHERE sku = 'OTU-100SL';
UPDATE product SET slug = 'lames-de-bistouri-steriles-paramount-n-11' WHERE sku = 'PAR-BLADE-11';
UPDATE product SET slug = 'lames-de-bistouri-steriles-paramount-n-15' WHERE sku = 'PAR-BLADE-15';
UPDATE product SET slug = 'otu-a-systeme-dimagerie-pour-ureter' WHERE sku = 'OTU-A';
UPDATE product SET slug = 'ne176520-seringue-luer-slip-seringue-' WHERE sku = 'NE176520';
UPDATE product SET slug = 'kit-soin-dentaire-essentiel' WHERE sku = 'KIT-DENT-001';
UPDATE product SET slug = 'speculum-nasal-greatcare-multi-tailles' WHERE sku = 'GRE-Z2R5B6';
